apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: smart-canteen
  labels:
    app: nacos
spec:
  ports:
    - name: http
      port: 8848
      targetPort: 8848
    - name: grpc
      port: 9848
      targetPort: 9848
  selector:
    app: nacos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: smart-canteen
  labels:
    app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:v2.3.2
          env:
            - name: MODE
              value: standalone
            - name: PREFER_HOST_MODE
              value: hostname
          ports:
            - containerPort: 8848
            - containerPort: 9848
          readinessProbe:
            httpGet:
              path: /nacos/v1/console/health/readiness
              port: 8848
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /nacos/v1/console/health/liveness
              port: 8848
            initialDelaySeconds: 30
            periodSeconds: 20
